version: "3.8"

services:
  chat-multi-book:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - vector_data:/app/vectorstore

volumes:
  vector_data:
